### ISSUE TITLE
Bug dans la gestion des couleurs

### ISSUE THREAD

**Issue by AUDEOUD** [maieul/eledform#4]
L'insertion de couleurs dans le texte colore aussi les versets, séparateurs de colonnes, et parfois aussi le texte complet des
![bug](https://f.cloud.github.com/assets/3676326/187683/d88b3428-7d7e-11e2-83b9-ef9cf8287820.jpg)
 variantes en bas de page.

**Comment by maieul** [comment]
ceci est un problème reledpar/reledmac.
