### ISSUE TITLE
Bug in typesetting identical variant from different manuscripts

### ISSUE THREAD

**Issue by carlodri** [maieul/eledform#5]
It seems to me like there is a bug in typesetting an identical variant from different manuscripts. For example:
```latex
 \var{ergo}{}{{A,B}{enim}}
```
gives this as a result:

![screen shot 2013-12-29 at 00 22 26](https://f.cloud.github.com/assets/5230366/1818649/faf624e2-7016-11e3-8c06-5f507c8d11d6.png)

I have the following options set in the preamble (in case it matters):
```latex
\varseparator{;\space}
\parafootsep{$||$ }
\manvarseparator{ $\rightarrow$ }	
```
and I'm using V1.0

**Comment by baem2** [comment]
This is still happening: For some reason "B" becomes part of the lemma and is printed behind the manvarseparator.

Here's a complete MWE:

```
\documentclass[a4paper,12pt]{article}
\usepackage[T1]{fontenc}
\usepackage[latin]{babel}
\usepackage[utf8]{inputenx}
\usepackage{eledform}

\footparagraph{A} 
\manuscript{A,B,C}

\begin{document}
\beginnumbering
\pstart
Lorem \var{ipsam}{}{{A,B}{ipsum}} dolor sit amet, con sectetuer adipiscing elit. Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis.
\pend
\endnumbering
\end{document}
```

**Comment by maieul** [comment]
sorry. I have decided to stop maintenance of eledform. I have no time for that and I prefer to concentrate on reledmac/reledpar.

**Comment by maieul** [comment]
the problem was you use

`````
var{ipsam}{}{{A,B}{ipsum}}
`````
and not

`````
var{ipsam}{}{{{A,B}{ipsum}}}
`````

but I have dediced to forget it, and there will be no replacement. Eledform was not a soo good idea.
